### ISSUE TITLE
Error when is_check_genotype = FALSE, is_dosage = FALSE

### ISSUE THREAD

**Issue by simonvandekar** [lin-lab/iSKAT-GESAT#1]
iSKAT errors when is_check_genotype = FALSE, is_dosage = FALSE. After fixing this error others appear that are related to the ridge.select.linear function:
Error in solve.default(transW %*% W + temp, transW) : 
  system is computationally singular: reciprocal condition number = 4.96825e-20

Here is a MWE:

E = matrix(rbinom(100, size = 1, prob=.5))
Y = matrix(rnorm(100))
Z = matrix(rnorm(1000), nrow=100)

### Run iSKAT ###
source('~/Box Sync/collaborative/iSKAT/iSKATmod.R')
test = iSKAT.mod(Z, Y, E, is_check_genotype = FALSE, is_dosage = FALSE, missing_cutoff = 1)

Thanks!

**Comment by shiandy** [comment]
Hi,

I contacted Dr. Xinyi Lin, the first author of the iSKAT paper, and worked with her on a fix for this. There is no longer an error when is_check_genotype = FALSE and is_dosage = FALSE. Additionally, the error message that you got is because the function does some search over some lambda values, and might fail for some values of lambda, particularly when the sample size is small. If the search fails for some values of lambda, the error message pops up, but the search keeps on going until it finds the final selected lambda, and the iSKAT function keeps running. So, if you check the value of test, you will see that it actually has the iSKAT return value. I've also fixed the error handling to catch this error message.

Thanks for pointing this out to us! Hope this fixes your issue.
